### ISSUE TITLE
Master CI/CD should trigger an acceptance tests run

### ISSUE THREAD

**Issue by QubitPi** [paion-data/aristotle#20]
Aristotle's acceptance tests looks pretty well done. [This repo](https://github.com/paion-data/aristotle-acceptance-tests/tree/master) will become increasingly important as we move on. Here is how it is positioned in Aristotle's ecosystem:

![CICD](https://github.com/user-attachments/assets/1293c9e7-0d0b-43ab-9db9-cc556b81d0d2)

> [!NOTE]  
>
> `aristotle-release-definition` will be another repo later that [I am responsible for](https://github.com/paion-data/aristotle/issues/21). 
>
> The diagram above adapts Yahoo's "三件套" strategy for all of their webservices:
>
> 1. a main repo (maintained by developers)
> 2. a mandatory acceptance tests repo (maintained by developers & business team)
> 3. a release definition repo that handles all deployments (maintained by a team's architect)
>
> By the way, they manage their internal Hadoop infrastructure this way as well 😉

We can see that if acceptance tests fail, our code won't deploy to production. This is why "acceptance tests" are also called "gatekeeper tests" and acceptance/gatekeeper tests have been used in Yahoo for all backend projects. This way, we __are sure that every lines of code change does not break our software in any possible way__

To make things happen, we will need to do the following first:

__Upon [aristotle's CI/CD](https://github.com/paion-data/aristotle/actions) runs _successfully_, the acceptance tests should automatically run immediately__

Here are the steps:

1. Implement CI/CD in `aristotle-acceptance-tests` repo with the following logics

   1. Standup [Aristotle Docker](https://github.com/paion-data/aristotle/blob/master/docker-compose.yml) (or in whatever way you prefer as long as the webservice is physically running)
   2. Run all acceptance tests

2. Add the following at the bottom of Aristotle's CI/CD:

   ```yaml
   triggering:
     name: Triggering Aristotle Acceptance Tests CI/CD
     needs: [tests, deploy-docs]
     if: github.ref == 'refs/heads/master'
     runs-on: ubuntu-latest
     steps:
       - name: Trigger downstream CI/CD
         uses: peter-evans/repository-dispatch@v2
         with:
           token: ${{ secrets.ARISTOTLE_DOWNSTREAM_CICD_TRIGGER_TOKEN }}
           repository: paion-data/aristotle-acceptance-tests
           event-type: aristotle-changes
   ```

   See [peter-evans/repository-dispatch](https://github.com/peter-evans/repository-dispatch) documentation for how to setup `ARISTOTLE_DOWNSTREAM_CICD_TRIGGER_TOKEN`

2. In `aristotle-acceptance-tests`'s CI/CD, add a [repository_dispatch trigger](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#repository_dispatch): 

   ```yaml
   "on":
     pull_request:
     push:
       branches:
         - master
     repository_dispatch:
       types: [aristotle-changes]
   ```
